cmd:
  lock:
    leetcode: ../leetcode.json
    algorithms: ../algorithms.json
  generation:
    readme: ../README.md
    algorithms: ../algorithms
  params:
    operation-name: question
    leetcode-com: https://leetcode.com
    graphql: https://leetcode.com/graphql
    problems-all-url: https://leetcode.com/api/problems/all/
    description: https://leetcode.com/problems/%v/description/
    lang: go
  template:
    solution: .leetcode-cli/solution.tpl.txt
    problem: .leetcode-cli/problem.tpl.txt
    readme: .leetcode-cli/readme.tpl.md
    unittest: .leetcode-cli/unittest.tpl.txt